declare const transformProps: (props: any) => {
    formProps: any;
    schema: any;
    onFinish: any;
    beforeFinish: any;
    onMount: any;
    watch: any;
    readOnly: any;
    column: any;
    mapping: any;
    debugCss: any;
    locale: any;
    configProvider: any;
    builtOperation: any;
    form: any;
    labelWidth: any;
    allCollapsed: any;
    debounceInput: any;
    validateMessages: any;
    debug: any;
    id: any;
    onFinishFailed: any;
    removeHiddenData: any;
    operateExtra: any;
    logOnMount: any;
    logOnSubmit: any;
    labelCol: any;
    fieldCol: any;
    maxWidth: any;
    hiddenSubmitButton: any;
    hasExportButton: any;
    exportFunc: any;
};
export default transformProps;
